### PR TITLE
Firebird database backup for easier start.

### PR DESCRIPTION
**Pull request by cincuranet**
Looks like the SQLite database is in the repo, so I included also Firebird database, so the script and data are not to be searched around. After the #44 is merged, this can be considered for merge. Feel free to reject if the DB should not be there.

### CODE REVIEW

**Comment by sebastienros** [comment]
Does Firebird work server-less?

**Comment by cincuranet** [comment]
It could. But then native library is also needed.

**Comment by sebastienros** [comment]
Then can you provide a SQL script instead? It would be easier, also for maintenance, than the binary snapshot. Examples here:
- https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/toolset/databases/postgres/create-postgres.sql
- https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/toolset/databases/mysql/create.sql

**Comment by cincuranet** [comment]
Do you want only `fortune` table in that script (because that's only [what's used](https://github.com/aspnet/DataAccessPerformance/blob/master/src/BenchmarkDb/Program.cs#L24)) or same complete script?

**Comment by sebastienros** [comment]
Please do both if that's not too much work, because we might need it if we want to test the data updates scenarios too

**Comment by cincuranet** [comment]
OK, done in #47 and #48.

**Pull request closed without merging**
